# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=30)),
                ('set_value', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
